config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root 'graphic#index'
  get 'xlss' => 'graphic#xlss'
  post 'xlss' => 'graphic#xlss'
  post 'rebuild' => 'topology#rebuild'
  get 'rebuild' => 'topology#rebuild'
  get 'check_email', to: 'user#check_email'
  get 'check_mac', to: 'switches#check_mac'
  get 'adminpanel' , to: 'adminpanel#index'
  post '/region', to: 'adminpanel#region_create', as: 'region_index'
  get '/region', to: 'adminpanel#region_create'
  post '/group', to: 'adminpanel#group_create', as: 'group_index'
  get '/group', to: 'adminpanel#group_create'
  patch '/group', to: 'adminpanel#group_update'
  post '/group_perm', to: 'adminpanel#group_perm', as: 'group_perm'
  get '/group_perm', to: 'adminpanel#group_perm'
  #get 'sessions' => 'sessions#new', as: 'sessions_new'
  get 'sessions/login' => 'sessions#login'
  post 'sessions/login' => 'sessions#login'
  get 'logout' => 'sessions#logout'
  post 'logout' => 'sessions#logout'
  get 'graphic/month' => 'graphic#month'
  post 'graphic/month' => 'graphic#month'
  get 'group_region_perm' => 'adminpanel#group_region_perm'
  post 'group_region_perm' => 'adminpanel#group_region_perm'
  get 'aggr_report' => 'switches#aggr_report'
  post 'aggr_report' => 'switches#aggr_report'
  patch 'change_password' => 'user#change_password'
  post 'forgot_password' => 'user#forgot_password'
  get 'forgot_password' => 'user#forgot_password'
  get 'reset_password' => 'user#reset_password'
  post 'reset_password' => 'user#reset_password'
  patch '/region', to: 'adminpanel#region_update'
  delete '/region/:id(.:format)', to: 'adminpanel#region_destroy', as: 'region_destroy'
  delete '/group/:id(.:format)', to: 'adminpanel#group_destroy', as: 'group_destroy'
  post 'managerings' => 'managerings#index'
  get 'managerings' => 'managerings#index'
  patch 'ring/:id(.:format)' => 'topology#ring_update', as: 'ring_upd'
  post 'ring_add' => 'topology#ring_add'
  delete '/ring/:id(.:format)', to: 'topology#ring_top_del', as: 'ring_destroy'
  #get 'ring' => 'topology#ring_update'
  post 'show_topology' => 'topology#index'
  get 'topology_menu' => 'topology#menu'
  post 'synchronize' => 'switches#synchronize'
  get 'stolen_list' => 'switches#stolen_list'
  get 'sw_loggs_event' => 'sw_loggs#event_notice'
  get 'xml_user' => 'user#xml_user'
  get 'ports_error_count' => 'port_errors#errors_count'
  get 'sw_instaled_list_path' => 'switches#inst_change_list'
post 'notify_port_error' => 'port_errors#notify'

  resources :user
  resources :switches
  resources :graphic
  resources :transport
  resources :topology
  resources :sw_loggs
  resources :sw_loggs_filter, :controller => "sw_loggs"
  resources :port_errors
#resources :sessions
end

app/controllers/adminpanel_controller.rb
class AdminpanelController < ApplicationController

  def index
   @group_all = Group.all
   @region = Region.all
  end


  def group_create
 @group = Group.create(group_params)
 if @group.persisted?
   @group_all = Group.all
   respond_to do |format|
     format.html
     format.js
   end
 end
  end


  def group_update
    group = Group.find(params[:id])
    @group = group.update(group_params)
    if @group
      respond_to do |format|
        format.js
      end
    end
  end

  def group_destroy
    @group = Group.destroy(params[:id])
    respond_to do |format|
      format.js
    end
  end


  def group_perm
    @perm = GroupPermission.create(group_permission)
    GroupPermission.destroy(group_perm_to_delete)
  end


  def group_region_perm
    params[:region_ids] ||= []
group = Group.find(params[:id])
arr = group.RegionPermission.map(&:region_id)
    val_add = params[:region_ids] - arr

    val_del = Region.all.map(&:id) - params[:region_ids]
    group.RegionPermission.where(region_id: val_del).destroy_all
    if val_add.empty?

    else

      # region_permission = Hash[ *val_add.collect { |val| ["region_id", val] }.flatten]


      region_permission = []
      val_add.each do |val|
        region_permission << {"region_id" => val}
      end


      puts region_permission

      group.RegionPermission.create(region_permission)
    end
  end



  def region_create
    service = RegionService.new(params)

    if service.perform
      @region = Region.all
      respond_to do |format|
        format.html
        format.js
      end
    end
  end


  def region_update
    region = Region.find(params[:id])
    @region = region.update(region_params)
    if @region
      respond_to do |format|
        format.js
      end
    end
  end

  def region_destroy
    @region = Region.destroy(params[:id])
    respond_to do |format|
      #format.html
      format.js
    end
  end



  private


  def group_permission
    arr =[]
    path = self.class.to_s + action_name.to_s
    if params[:group_ids].nil?

    else
    params[:group_ids].each do |id|
      if GroupPermission.where(group_id: id, url_path: path).nil?

        else
          arr << {url_path: params[:url_path], group_id: id, permite: 1}
      end
    end
    end
    return arr
  end



  def group_perm_to_delete
    if params[:group_ids].nil?
      arr = Group.all.map(&:id)
    else
      arr = Group.all.map(&:id) - params[:group_ids].map{|i| i.to_i}
    end
       res = GroupPermission.where(group_id: arr, url_path: params[:url_path]).map(&:id)
    return res
  end


  def group_params
    params.require(:group).permit(:name, :group_type, :remove, :create)
  end

  def region_params
    params.require(:region).permit(:name)
  end
end

app/helpers/adminpanel_helper.rb
module AdminpanelHelper
end

app/views/adminpanel/_group_permission.html.erb
<% @group_all.each do |group| %>
    <div class="panel panel-primary">
      <div class="panel-heading"><%= group.name%></div>

      <div class="panel-body">

        <%= form_for :group_perm, :url => group_region_perm_path({id: group.id}), remote: true do |reg| %>

            <% @region.each do |region| %>
                <%= check_box_tag 'region_ids[]', region.id, group.RegionPermission.map(&:region_id).include?(region.id)  %>
                <%= region.name %> <br>
            <% end %>
            <%= reg.submit "Применить", :class=>"btn btn-default"%>
    <% end %>
      </div>
    </div>
<% end %>

app/views/adminpanel/_show_group.html.erb
<% @group_all.each do |group| %>
    <tr id="<%= group.id%>">
      <td><button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatepost_<%= group.id %>">
        <%= group.name %>
      </button></td>
      <td><%= link_to "(удалить)", group_destroy_path(group.id), method: :delete, data: { confirm: 'Вы уверены?' }, remote: true%></td>

    </tr>

    <!-- Modal - update posts -->
    <%= form_for group, :url=> group_path(id: group.id), :method => :patch,remote: true do |f| %>
        <div class="modal fade" id="myupdatepost_<%= group.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Edit</h4>
              </div>
              <div class="modal-body">
                <%= f.text_field :name%>
                <div class="form-group">
                  <%= f.label :group_type, 'супер группа' %>
                  <%= f.check_box :group_type, checked: group.group_type == 'admin' %>
                  <%= f.label :remove, 'удаление' %>
                  <%= f.check_box :remove %>
                  <%= f.label :create, 'создание ' %>
                  <%= f.check_box :create %>
                </div>

              </div>
              <div class="modal-footer">
                <button type="button" id="myupdatebutton_<%= group.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
                <%= submit_tag "Update", class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    <!-- Modal -->

<% end %>

app/views/adminpanel/_show_region.html.erb
<% @region.each do |region| %>

    <!-- Modal - update posts -->
    <%= form_for region, :url=> region_path(id: region.id), :method => :patch,remote: true do |f| %>
        <div class="modal fade" id="myupdatepost_<%= region.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Edit</h4>
              </div>
              <div class="modal-body">
                <%= f.text_field :name%>
              </div>
              <div class="modal-footer">
                <button type="button" id="myupdatebutton_<%= region.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
                <%= submit_tag "Update", class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    <!-- Modal -->


    <tr id="<%= region.id%>">
      <td><button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatepost_<%= region.id %>">
        <%= region.name %>
      </button></td>
      <td><%= link_to "(удалить)", region_destroy_path(region.id), method: :delete, data: { confirm: 'Вы действительно хотите удалить регион? Учтите что все графики и пользователи так же будут удалены.' }, remote: true%></td>

    </tr>
<% end %>

app/views/adminpanel/group_create.js.erb
$("#group_table").empty();
$("#group_table").append("<%= j render 'show_group' %>");

app/views/adminpanel/group_destroy.js.erb
$('tr#<%= @group.id %>').fadeOut();

app/views/adminpanel/index.html.erb
<%= javascript_include_tag "adminpanel.js"%>
<div class="container">

  <div class="span5 fill">
    <button id="regions">Регионы</button>
    <button id="groups">Группы</button>

    <div id="region" style="display: none; padding-top: 5%;">
      <table class="table" style="width: 40%;">
        <thead>
        <tr>
          <th>Имя ЦОА/Региона/Отдела</th>
          <th> </th>
        </tr>
        </thead>
          <tbody id="region_table">
          <%=  render 'show_region' %>
        </tbody>
      </table>



      <div id="new_task" style="padding-top: 2%;">
        <%= form_for :region, url: region_index_path, :html => {:class=>"form-inline"}, remote: true do |u| %>

            <div class="form-group">
              <%= u.label :name, 'название отдела/региона' %>
              <%= u.text_field :name, :class=>"form-control input-sm" %>
            </div>

            <%= u.submit "Добавить", :class=>"btn btn-default"%>
        <% end %>
      </div>
    </div>



    <div id="group" style="display: none; padding-top: 5%;">

      <table class="table" style="width: 40%;">
        <thead>
        <tr>
          <th>Имя группы</th>
          <th> Тип группы</th>
          <th> </th>
          <th> <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal">права групп</button></th>
        </tr>

        </thead>
        <tbody id="group_table">
        <%= render 'show_group'%>
        </tbody>
      </table>

      <%= form_for :group, url: group_index_path, :html => {:class=>"form-inline"}, remote: true do |g| %>
          <div class="form-group">
            <%= g.label :name, 'Имя Группы' %>
            <%= g.text_field :name, :class=>"form-control input-sm" %>
          </div>
          <div class="form-group">
          <%= g.label :group_type, 'супер группа' %>
          <%= g.check_box :group_type %>
            <%= g.label :remove, 'удаление' %>
            <%= g.check_box :remove %>
            <%= g.label :create, 'создание ' %>
            <%= g.check_box :create %>
          </div>
          <%= g.submit "Добавить", :class=>"btn btn-default"%>
      <% end %>

          </div>

    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Редактировать права Группы</h4> <span class="glyphicon glyphicon-alert"></span> Для каждой группы можно установить разрешение на просмотр региона/ЦОА
          </div>
          <div class="modal-body">
            <%= render 'group_permission' %>


          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>

      </div>
    </div>


  </div>
</div>

app/views/adminpanel/region_create.js.erb
$("#region_table").empty();
$("#region_table").append("<%= j render 'show_region' %>");

app/views/adminpanel/region_destroy.js.erb
$('tr#<%= @region.id %>').fadeOut();