config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root 'graphic#index'
  get 'xlss' => 'graphic#xlss'
  post 'xlss' => 'graphic#xlss'
  post 'rebuild' => 'topology#rebuild'
  get 'rebuild' => 'topology#rebuild'
  get 'check_email', to: 'user#check_email'
  get 'check_mac', to: 'switches#check_mac'
  get 'adminpanel' , to: 'adminpanel#index'
  post '/region', to: 'adminpanel#region_create', as: 'region_index'
  get '/region', to: 'adminpanel#region_create'
  post '/group', to: 'adminpanel#group_create', as: 'group_index'
  get '/group', to: 'adminpanel#group_create'
  patch '/group', to: 'adminpanel#group_update'
  post '/group_perm', to: 'adminpanel#group_perm', as: 'group_perm'
  get '/group_perm', to: 'adminpanel#group_perm'
  #get 'sessions' => 'sessions#new', as: 'sessions_new'
  get 'sessions/login' => 'sessions#login'
  post 'sessions/login' => 'sessions#login'
  get 'logout' => 'sessions#logout'
  post 'logout' => 'sessions#logout'
  get 'graphic/month' => 'graphic#month'
  post 'graphic/month' => 'graphic#month'
  get 'group_region_perm' => 'adminpanel#group_region_perm'
  post 'group_region_perm' => 'adminpanel#group_region_perm'
  get 'aggr_report' => 'switches#aggr_report'
  post 'aggr_report' => 'switches#aggr_report'
  patch 'change_password' => 'user#change_password'
  post 'forgot_password' => 'user#forgot_password'
  get 'forgot_password' => 'user#forgot_password'
  get 'reset_password' => 'user#reset_password'
  post 'reset_password' => 'user#reset_password'
  patch '/region', to: 'adminpanel#region_update'
  delete '/region/:id(.:format)', to: 'adminpanel#region_destroy', as: 'region_destroy'
  delete '/group/:id(.:format)', to: 'adminpanel#group_destroy', as: 'group_destroy'
  post 'managerings' => 'managerings#index'
  get 'managerings' => 'managerings#index'
  patch 'ring/:id(.:format)' => 'topology#ring_update', as: 'ring_upd'
  post 'ring_add' => 'topology#ring_add'
  delete '/ring/:id(.:format)', to: 'topology#ring_top_del', as: 'ring_destroy'
  #get 'ring' => 'topology#ring_update'
  post 'show_topology' => 'topology#index'
  get 'topology_menu' => 'topology#menu'
  post 'synchronize' => 'switches#synchronize'
  get 'stolen_list' => 'switches#stolen_list'
  get 'sw_loggs_event' => 'sw_loggs#event_notice'
  get 'xml_user' => 'user#xml_user'
  get 'ports_error_count' => 'port_errors#errors_count'
  get 'sw_instaled_list_path' => 'switches#inst_change_list'
post 'notify_port_error' => 'port_errors#notify'

  resources :user
  resources :switches
  resources :graphic
  resources :transport
  resources :topology
  resources :sw_loggs
  resources :sw_loggs_filter, :controller => "sw_loggs"
  resources :port_errors
#resources :sessions
end

app/models/user.rb
class User < ApplicationRecord
  include Authentication
  #has_secure_password
  belongs_to :group
  belongs_to :region
  has_one :MailDeliver
  has_many :UserPermission
  has_many :graphic, :dependent => :destroy
  attr_accessor :password, :password_confirmation, :reset_pass, :name, :secondname,:mail_recive
  before_update :check_what_need_to_reset, :mail_recent
  before_create :user_default_option, :createfullname
  #before_save :createfullname
  #after_initialize :set_default_values
  validates :name, :presence => { :message => "Поле имя не может быть пустым"}, :on => :create
  validates :secondname, :presence => { :message => "Поле имя не может быть пустым"}, :on => :create
  validates :email, :presence => { :message => "Поле почта не может быть пустым"}, :on => :create
  validates :email, uniqueness: true






  def mail_recent
    if mail_recive == '1'
      if self.MailDeliver.nil?
        self.create_MailDeliver(:name => self.fullname, :email => self.email)
      else
        self.MailDeliver.update_attributes(:name => self.fullname, :email => self.email)
      end
    else
      self.MailDeliver.destroy unless  self.MailDeliver.nil?
    end
  end

  def pass_upd(password, password_confirmation)
    #reg = /\A\w+([A-Za-z])\w{6,}([A-Za-z])\w+\z/
    reg = /\A\w+([A-Za-z])\w+/
    if password.match(reg) and password_confirmation.match(reg) and password == password_confirmation
      self.password = password
      encrypt_password
      true
    else

      false
    end
  end

  def pass_active
    self.passactive = "1"
    self.save
  end


  # def fullname
  #   self.name + " " + self.secondname
  # end



  def self.search(search, ids)

    if search
      User.where(:region => (ids))
          .includes(:region)
          .where('users.fullname LIKE :search  OR regions.name LIKE :search OR users.email LIKE :search',search: "%#{search}%").references(:region)
    else
      where(region: ids)
    end
  #all
  end



  def reset_password
    self.passactive = nil
    # self.salt = nil
    #
    # self.encrypted_password = nil
    user_default_option
    #encrypt_password
    self.save
  end


  private

   def check_what_need_to_reset
     if reset_pass == "1"
     self.passactive = nil
  #   # self.salt = nil
  #   #
  #   # self.encrypted_password = nil
  user_default_option
     encrypt_password
       end
   end

  def should_validate_password?
    pass_valid != '1'
  end

  def user_default_option
    self.password ||= "123456"
    encrypt_password
  end


  def encrypt_password

    self.salt = BCrypt::Engine.generate_salt
    self.encrypted_password = BCrypt::Engine.hash_secret(password, self.salt)
  end



  def createfullname
    if name.present? and secondname.present?
      self.fullname = secondname + " " + name
      #self.save
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
   def xml_user
    @user = User.all
  end
######################## password section
  def change_password
    @user = userfind
    if @user.pass_upd(params[:user][:password], params[:user][:password_confirmation])
      @user.pass_active
      redirect_to user_path(@user.id)
    else
      render "sessions/new"
    end
  end



  def forgot_password
    if params[:user].present?
  user = User.find_by_email(params[:user][:email])
    if user
      safe_link = SecureRandom.hex[0,20]
  user.update(recover_url: safe_link, token_date: Time.now.strftime("%Y-%m-%d %H:%M") )
      UserMailer.reset_password(user.email, "Для восстановления пароля перейдите по ссылке #{request.base_url}/reset_password?id=#{user.id}&token=#{safe_link}").deliver_now
      redirect_to  sessions_new_path
    end
      end
  end

  def reset_password
    #begin
    user = userfind
    user.update(recover_url: nil, token_date: nil) if user.token_date < 2.hours.ago
    if user.recover_url == params[:token]
      user.reset_password

      user.update(recover_url: nil, token_date: nil)
      UserMailer.reset_password(user.email, "Ваш пароль был сброшен. Пароль по умолчанию: '123456'.").deliver_now
      redirect_to sessions_new_path
    else
      render "error"
     # end
    end
  end


  ########################### password section end
  def check_email
    respond_to do |format|
      @user = User.where(:email => params[:email])
      @some = {val: @user.exists?}
      format.json {render json: @some}
    end
  end

  def new
    if url_validate(self.class.to_s + action_name )
    @user = UserService.new(nil)
    else
      redirect_to root_path
    end
  end


  def show

    if user_can_see
      @user = userfind
    else
      render "error/user_error"
      end
  end


  def edit
    if user_can_see
      if current_user.group.remove == "1" or  userfind.id == current_user.id or current_user.group.group_type == "admin"
      @user = userfind
      else
        render 'error/user_error'
        end
    else
      render 'error/user_error'
      end
  end


  def index
    if url_validate(self.class.to_s + action_name )
    if current_user.group.group_type == "admin"
      ids = Region.all.map(&:id)
    else
    ids = current_user.group.RegionPermission.map(&:region_id) + [current_user.region_id]
    end
    @user =  User.search(params[:search], ids)
    else
      redirect_to root_path
    end
  end



  def create

      #service object
      @user = UserService.(params)
    #@user = User.create(new_user)
      if @user.errors.empty?
      redirect_to  root_path
        return
      else
        #@user = @user.errors
     render :new
    end


  end



  def update
    @user = userfind
    #@user_list = @user
    if @user.update(upd_user)
       redirect_to user_path(@user.id)
    # else
    #   case user_params[:pass_valid]
    #     when "1"
    #     else
    #       render "login"
    #   end
     end
  end






  def shortupdate
    respond_to do |format|
        format.html
        format.js
      end

  end


  def destroy
    if current_user.group.remove == "1"
    @user = userfind
    @user.destroy
    respond_to do |destr|
      destr.html
      destr.js
    end
    end
  end
private

  def user_can_see
  perm = [current_user.region_id] + current_user.group.RegionPermission.map(&:region_id)
    if perm.include? (userfind.region_id)
      true
    elsif current_user.group.group_type == "admin"
      true
    else
      false
    end
  end



  def userfind
    User.find(params[:id])
  end


  def short_update_params
    params.require(:user_short).permit(:fullname, :phone, :email)
  end

def upd_user
  params.require(:user).permit(:name, :secondname,:phone, :email, :region_id, :fullname, :reset_pass, :group_id, :mail_recive )
end
  def new_user
    params.require(:user).permit(:name, :secondname, :phone, :email, :region_id)
  end
end

app/helpers/user_helper.rb
module UserHelper

  def split_phone(str)
    if str.match(/\//)

      phone1, phone2 = str.split("/")

      return [phone1.gsub(/-|\s/, ""), phone2.gsub(/-|\s/, "")]
    else

      return [str.gsub(/-|\s/, ""),""]
    end

  end

  def user_can_manage(user, obj)
    if user.group.group_type == "admin"
      true
    elsif user.group.remove == true and user.group.RegionPermission.map(&:region_id).include?(obj.region_id)
      true
    end
  end


  def select_user_list
    if current_user.group.group_type == 'admin'
      User.all.collect{|u| [u.fullname + " " + "(#{u.region.name})", u.id]}
    else
     ids = current_user.group.RegionPermission.map(&:region_id) + [current_user.region_id]
    return User.where(region_id: ids).collect{|u| [u.fullname + " " + "(#{u.region.name})", u.id]}
    end
  end

end

app/views/user/_error.html.erb
Произошла непредвиденная ошибка.

app/views/user/_searchresult.html.erb
<% @user.each do |users|%>

    <tr id="my<%= users.id%>">
      <td >

        <%= link_to users.fullname, user_path(users) %>

      </td>
      <td><%= users.phone%></td>
      <td class="text-center">

      </td>
      <td>
        <%= users.email %>
      </td>
      <td style="width: 20%;">
        <%= link_to user_path(users) , :class=>"table-link" 	do%>
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
                                            </span>
        <% end %>
        <% if current_user.present? and user_can_manage(current_user, users) %>
        <%= link_to edit_user_path(users, :update => "1") , :class=>"table-link", remote: true 	do%>
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                            </span>
        <% end %>
            <%= link_to user_path(users), method: :delete,data: { confirm: 'Вы уверены?' }, remote: true, :class=>"table-link danger " do%>

                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                            </span>
            <% end %>
        <% end %>

      </td>

    </tr>
    <tr id="<%= users.id%>" class="edit_test">


    </tr>
<% end%>

app/views/user/create.js.erb
<%
@errors = []
@user.errors.errors.map {|k,v|

v.each do |arr|

arr.each_slice(2) do |x,a|
@errors << k.to_s + '_' + x.to_s
@errors << a[0]
end
end
}
%>


<% @errors.each_slice(2) do |error, val| %>

$( "#<%= error %>" ).wrap( "<div class='field_with_errors'></div>" );
<% end %>

app/views/user/edit.html.erb
<div class="container">
  <div class="span5 fill">


    <%= form_for @user, method: :patch, :html => {:class=>"form-horizontal"}, remote: false do |f| %>
        <fieldset>
          <!-- Form Name -->
          <legend>Обновление профиля</legend>
          <% if @user.errors.any? %>
              <div id="error_explanation">

                <ul>
                  <% @user.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="form-group">

            <%= f.label :fullname, "Имя и фамилия:", :class=> "col-md-4 control-label" %>
            <div class="col-md-4">
              <%= f.text_field :fullname, :class=>"form-control input-md" %>
            </div>
          </div>







          <div class="form-group">
            <%= f.label :phone, "Телефон", :class=> "col-md-4 control-label" %>
            <div class="col-md-4">
              <%= f.text_field :phone , :class=>"form-control input-md"%>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :email, "Почта", :class=> "col-md-4 control-label"%>
            <div class="col-md-4">
              <%= f.text_field :email, :class=>"form-control input-md" %>

            </div>
          </div>
          <% if current_user.group.group_type == "admin" %>

              <div class="form-group">
                <%= f.label :region_id, 'ЦОА *',  :class=> "col-md-4 control-label"%>
                <div class="col-md-4">
                  <%= f.select :region_id, (Region.all.collect{|u| [u.name, u.id]}),{ :prompt => "ЦОА"},  :class=>"form-control"%>

                </div>
              </div>
<%#= f.fields_for :MailDeliver do |build|%>
<%#= build.text_field :name, :class=>"form-control input-md" %>
              <div class="form-group">
                <%= f.label :mail_recive, "Уведомлять если не составлен график на завтра",  :class=> "col-md-4 control-label"%>
                <div class="col-md-4">
                  <%= f.check_box :mail_recive, {:checked=> @user.MailDeliver.present?} %>
                </div>
              </div>
<%# end %>



              <div class="form-group">
                <%= f.label :reset_pass, "Сбросить пароль",  :class=> "col-md-4 control-label"%>
                <div class="col-md-4">
                  <%= f.check_box :reset_pass %>
                </div>
              </div>

              <div class="form-group">
                <%= label :reset_pass, "Редактировать права",  :class=> "col-md-4 control-label"%>
                <div class="col-md-4">
                  <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal">...</button>
                </div>
              </div>


              <div class="form-group">

                <%= f.label :group_id, "Группа", :class=> "col-md-4 control-label"%>
                <div class="col-md-4">
                  <%= f.select :group_id, (Group.all.collect{|g| [g.name, g.id]}),{ :prompt => "#{@user.group.name if @user.group != nil}"}, :class=>"form-control"%>

                </div>
              </div>
          <% end %>
          <div class="form-group">
            <%= f.label :vacstart, "Начало отпуска",  :class=> "col-md-4 control-label" %>
            <div class="col-md-4">
              <%= f.text_field :vacstart,  :class=>"vacs form-control input-md"%>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :vacend, "Конец отпуска",  :class=> "col-md-4 control-label" %>
            <div class="col-md-4">
              <%= f.text_field :vacend, :class=>"vacs form-control input-md"%>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="signup"></label>
            <div class="col-md-4">
              <%= f.submit "Изменить", :id=>"signup", :class=>"btn btn-info"%>
            </div>
          </div>

    <% end %>




    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Редактировать права пользователя</h4>
          </div>
          <div class="modal-body">







          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>

      </div>
    </div>

  </div>
</div>

app/views/user/forgot_password.html.erb
<div class="container">
  <div class="span5 fill">

    <%= form_for :user, :url => forgot_password_path do |f| %>
    <%= f.text_field :email %>
        <%= f.submit "отправить"%>
    <% end %>
  </div>
</div>

app/views/user/index.html.erb
<%= javascript_include_tag "user"%>
<div class="container">
  <div class="span5 fill">

    <div class="row">
      <div class="col-md-4 col-md-offset-3">
        <form action="" class="search-form">
          <div class="form-group has-feedback">
            <label for="search" class="sr-only">Search</label>
            <input type="text" class="form-control" name="search" id="my_search" placeholder="Введите имя, почту или регион">
            <span class="glyphicon glyphicon-search form-control-feedback"></span>
          </div>
        </form>
      </div>
    </div>
    <div id="result"></div>
    <hr>

    <div class="container bootstrap snippet">
      <div class="row">
        <div class="col-lg-12">
          <div class="main-box no-header clearfix">
            <div class="main-box-body clearfix">
              <div class="table-responsive">
                <table class="table user-list">
                  <thead>
                  <tr>
                    <th style="width: 40%;"><span>Пользователь</span></th>
                    <th style="width: 30%;"><span>Телефон</span></th>
                    <th style="width: 5%;" class="text-center"><span></span></th>
                    <th style="width: 15%;"><span>Почта</span></th>
                    <th style="width: 10%;">&nbsp;</th>
                  </tr>
                  </thead>
                  <tbody>

                  <%= render "searchresult" %>

                  </tbody>

                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/index.js.erb
$('tbody').empty();
$("tbody").html("<%= j render ('searchresult') %>");

app/views/user/new.html.erb
<%= javascript_include_tag "user" %>
<div class="container">
  <div class="span5 fill">


    <%= form_for :user, url: user_index_path, :html => {:name=>"forms", :class=>"form-horizontal"}, remote: false do |u| %>
    <%#= form_for @user, validate: true, :html => {:class=>"form-horizontal"} do |u| %>
        <fieldset>
          <!-- Form Name -->
          <legend>Регистрация</legend>
          <%= @user.errors.full_messages %>
          <% if @user.errors.any? %>

              <div id="error">
                <ul>
                  <% @user.errors.full_messages.each do |err| %>
                      <li><%= err%> </li>
                  <% end %>
                </ul>
              </div>
          <% end %>



          <div class="form-group">
            <%= u.label :secondname, 'Фамилия *', :class=> "col-md-4 control-label " %>
            <div class="col-md-4">
              <%= u.text_field :secondname, :class=>"form-control input-md " %>
            </div>
          </div>
          <div class="form-group">
            <%= u.label :name, 'Имя *', :class=> "col-md-4 control-label", :value=>"ssss" %>
            <div class="col-md-4">
              <%= u.text_field :name, :class=>"form-control input-md"  %>
            </div>

          </div>

          <div class="form-group">
            <%= u.label :phone, 'Номер телефона *', :class=> "col-md-4 control-label" %>

            <div class="col-md-4">
              <%= u.text_field :phone, :class=>"form-control input-md"  %>
            </div>
          </div>
          <div class="form-group">
            <%= u.label :email, 'Почта *',  :class=> "col-md-4 control-label"%>
            <div class="col-md-4">
              <%= u.text_field :email, :class=>"form-control input-md"  %>

            </div>
          </div>
          <div class="form-group">
            <%= u.label :region_id, 'ЦОА *',  :class=> "col-md-4 control-label"%>
            <div class="col-md-4">
              <%= u.select :region_id, (Region.all.collect{|u| [u.name, u.id]}),{ :prompt => "ЦОА"}, :class=>"form-control"%>

            </div>
          </div>


          <div class="form-group">
            <label class="col-md-4 control-label" for="signup"></label>
            <div class="col-md-4">
              <%= u.submit "Добавить", :id=>"signup", :class=>"btn btn-info"%>
            </div>
          </div>



        </fieldset>
    <% end %>



  </div>
</div>

app/views/user/shortupdate.js.erb
$( "#my<%= @user.id%>" ).html("<%= j render(@user)%>");

app/views/user/show.html.erb
<%#= stylesheet_link_tag    'graphics'%>



<div class="container">
  <div class="span5 fill">


    <br><br>
    <div class="container-fluid well span6">
      <div class="row-fluid">


        <div class="span8">
          <h3><%= @user.fullname %></h3>
          <h6>Почта:<%= @user.email %></h6>
          <h6>ЦОА:<%= @user.region.name %></h6>
          <h6>Телефон:<%= @user.phone %></h6>

        </div>

        <div class="span2">
          <div class="btn-group">
            <a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
              +
              <span class="icon-cog icon-white"></span><span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Редактировать профиль', edit_user_path(@user) %><span class="icon-wrench"></span></li>
              <li><span class="icon-trash"></span> </li>
            </ul>
          </div>
        </div>
      </div>
    </div>










    <br>                               Рабочие дни:
    <div id="articles">

      <%= calendar do |date| %>

          <%= date.day %>
          <% if @user.graphic.group_by(&:date)[date.to_s] %>
              <% @user.graphic.group_by(&:date)[date.to_s].each do |mm, graph|%>
                  Рабочий день<br>
<% if current_user.group.remove == true %>
                  <%#= link_to "удалить"(graphic_path(mm.id), 'Удалить') %>
<%= link_to "Удалить", graphic_path(mm.id) , method: :delete, data: { confirm: 'Вы уверены?' } %>
<%# else  %>
<%   end %>

              <% end %>
          <% end %>
      <% end %>

    </div>





  </div>
</div>