config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root 'graphic#index'
  get 'xlss' => 'graphic#xlss'
  post 'xlss' => 'graphic#xlss'
  post 'rebuild' => 'topology#rebuild'
  get 'rebuild' => 'topology#rebuild'
  get 'check_email', to: 'user#check_email'
  get 'check_mac', to: 'switches#check_mac'
  get 'adminpanel' , to: 'adminpanel#index'
  post '/region', to: 'adminpanel#region_create', as: 'region_index'
  get '/region', to: 'adminpanel#region_create'
  post '/group', to: 'adminpanel#group_create', as: 'group_index'
  get '/group', to: 'adminpanel#group_create'
  patch '/group', to: 'adminpanel#group_update'
  post '/group_perm', to: 'adminpanel#group_perm', as: 'group_perm'
  get '/group_perm', to: 'adminpanel#group_perm'
  #get 'sessions' => 'sessions#new', as: 'sessions_new'
  get 'sessions/login' => 'sessions#login'
  post 'sessions/login' => 'sessions#login'
  get 'logout' => 'sessions#logout'
  post 'logout' => 'sessions#logout'
  get 'graphic/month' => 'graphic#month'
  post 'graphic/month' => 'graphic#month'
  get 'group_region_perm' => 'adminpanel#group_region_perm'
  post 'group_region_perm' => 'adminpanel#group_region_perm'
  get 'aggr_report' => 'switches#aggr_report'
  post 'aggr_report' => 'switches#aggr_report'
  patch 'change_password' => 'user#change_password'
  post 'forgot_password' => 'user#forgot_password'
  get 'forgot_password' => 'user#forgot_password'
  get 'reset_password' => 'user#reset_password'
  post 'reset_password' => 'user#reset_password'
  patch '/region', to: 'adminpanel#region_update'
  delete '/region/:id(.:format)', to: 'adminpanel#region_destroy', as: 'region_destroy'
  delete '/group/:id(.:format)', to: 'adminpanel#group_destroy', as: 'group_destroy'
  post 'managerings' => 'managerings#index'
  get 'managerings' => 'managerings#index'
  patch 'ring/:id(.:format)' => 'topology#ring_update', as: 'ring_upd'
  post 'ring_add' => 'topology#ring_add'
  delete '/ring/:id(.:format)', to: 'topology#ring_top_del', as: 'ring_destroy'
  #get 'ring' => 'topology#ring_update'
  post 'show_topology' => 'topology#index'
  get 'topology_menu' => 'topology#menu'
  post 'synchronize' => 'switches#synchronize'
  get 'stolen_list' => 'switches#stolen_list'
  get 'sw_loggs_event' => 'sw_loggs#event_notice'
  get 'xml_user' => 'user#xml_user'
  get 'ports_error_count' => 'port_errors#errors_count'
  get 'sw_instaled_list_path' => 'switches#inst_change_list'
post 'notify_port_error' => 'port_errors#notify'

  resources :user
  resources :switches
  resources :graphic
  resources :transport
  resources :topology
  resources :sw_loggs
  resources :sw_loggs_filter, :controller => "sw_loggs"
  resources :port_errors
#resources :sessions
end

app/models/topology.rb
class Topology < ApplicationRecord
  belongs_to :ring
end

app/controllers/topology_controller.rb
class TopologyController < ApplicationController

  def topologymake
    rings_list = Ring.all.group_by(&:aggraddress).flatten

    t = TopologyService.new
    rings_list.each_slice(2) do |ip, val|
      hash = t.get_arp(ip,val)
      puts hash
      puts t.make_topology(val, hash)

    end
  end


  def rebuild
    api_con = ApiclientService.new
    token = api_con.get_token
    ring = Ring.find_by_pool(params[:pool])
    ring_sw = api_con.switch_get_loc(token, params[:pool])["sw_loc"].count
    t = TopologyService.new

    if t.fping(params[:pool]).count >= ring_sw
      hash = t.get_arp(ring.aggraddress,[ring])
      result = t.make_topology([ring], hash)
      status = 200
    else
      status = 404
    end
    respond_to do |format|
      format.html
      format.js {render :status => status}
    end
  end

  def index
    if url_validate(self.class.to_s + action_name )
      @ring = Ring.all.map(&:pool).group_by { |word| word[4..6] }

      if params[:ring] == nil
        pool = "Feed monkey"
      else
        top = TopologyService.new



        api_con = ApiclientService.new
        token = api_con.get_token

        ring = Ring.find_by_pool(params[:ring])
        topology = ring.topology.as_json
        arp = ring.ArpInfo.as_json
        status = top.fping(params[:ring])
        @status = []
        arp.each do |sw|
          if status.include? (sw["ip"])
            @status <<  {ip: sw["ip"], status: "1"}
          else
            @status <<  {ip: sw["ip"], status: "0"}
          end
        end
        @ring_loc = api_con.switch_get_loc(token, params[:ring])

        @all_ip = (topology+arp+@ring_loc["sw_loc"]).group_by{|h| h["ip"]}.map{|k,v| v.reduce(:merge)}.reject { |tp| tp["ip"] == params[:ring] + ".1" }


        tp_port = @all_ip.sort { |x, y| y["max_value"].to_i<=>x["max_value"].to_i }.group_by {|gei| gei["tpport"]}.map {|k,v| {port: k, ips:v.map{|ip|ip["ip"]}, lat: v[0]["lat"], lng: v[0]["lng"]}}

        @rings = []
        @all_ip.group_by{|g| g["lat"] if g["lat"] != nil}.each do |val|
          @next = []
          short_ips = val[1].map{|hash| hash["ip"].split('.')[3]}.join(',')
          nest_ips = val[1].map{|hash| hash["ip"]}
          ips = val[1].sort { |x, y| y["max_value"].to_i <=> x["max_value"].to_i}.map{|hash| hash["ip"]}

          main_lat = val[1][0]["lat"]
          main_lng = val[1][0]["lng"]

          @nest = [] #:nest=>[[50.413292, 30.642364], [50.421553, 30.639822]]
          @hash = [] #:hash=>[[{:ip=>"172.17.1.43", :port25=>"172.17.1.57", :port26=>"172.17.1.53", :port27=>"", :port28=>"172.17.1.61"}],...]
          val[1].sort { |x, y| y["max_value"].to_i<=>x["max_value"].to_i }.each do |sw_info|
            #
            [sw_info["port25"], sw_info["port26"], sw_info["port27"], sw_info["port28"]].each do |nest_sw|
              if nest_sw.nil?

              else

                sw = @all_ip.find {|ip| ip["ip"] == nest_sw}

                begin
                  lat = sw["lat"]
                  lng = sw["lng"]

                  @nest << [lat, lng] unless lat == nil or lat == main_lat or lng == main_lng
                  @hash << [sw_info.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}]
                  @next << sw["ip"]
                rescue => e
                  puts "#{e} in #{sw}"

                end
              end
            end
          end
          ##find prev main section

          main = val[1].max_by{|x| x["max_value"].to_i}.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}
          prewsw = @all_ip.find { |ip| [ip["port25"], ip["port26"], ip["port27"], ip["port28"]].include? (main[:ip]) }

          if prewsw.nil?
            prewsw = {:ip => "tp"}
          end
          #####
          #main_status = @status.find{|ip|ip[:ip] == main[:ip]}[:status]  "0"
          main_status = @status.find{|ip|ip[:ip] == main[:ip]} || {status: "0"}
          @rings << {ip: short_ips, lat: main_lat, lng: main_lng, nest: @nest, hash: @hash, ips: ips, main: prewsw.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}, next: @next - nest_ips, status: main_status[:status] ,all_status: @status, test: prewsw}
        end

        @gontop = {:tp => @ring_loc["tp_loc"], :tp_link => tp_port, :ring => @rings, :all_ip =>  @all_ip}

        @gonring = @all_ip.reject { |sw| sw if sw["lat"].nil? }.map {|v| v.inject({}){|memo,(k,v)| memo[k.to_sym] = v.to_s; memo}}

        respond_to do |format|
          format.html
          format.js

        end


      end

    else
      redirect_to root_path
    end
  end


  def show
    @ring = Ring.find(params[:id])
  end

  def menu
    #if url_validate(self.class.to_s + action_name )
    @rings = Ring.all.group_by(&:aggraddress)
    @ring_list = Ring.all
    #else
    # redirect_to root_path
    #end
  end

  def new
  end

  def ring_update
    ring = Ring.find(params[:id])
    @top = ring.update(ring_params)
  end

  def ring_add
    ring = Ring.find(params[:id])
    ring.topology.create(ring_params)
  end

  def ring_top_del
ring = Topology.find(params[:id])
    ring.destroy
  end

  def update
    @ring = Topology.find(params[:id])
    if @ring.update(top_params)
      #redirect_to @user
    else
    end

    respond_to do |format|

      format.html
      format.js
    end


  end


  def create
    #render plain: params[:topology].inspect
    #@ring = Ring.new(params.require(:topology).permit(:pool, :vlan, :build))
    @ring = Ring.create(ring_params)

    if  @ring.persisted?
      respond_to do |format|

        format.html
        format.js
      end
      #redirect_to new_topology_path
    else
      render 'show'
    end
  end


  def destroy
    @ring = Ring.find(params[:id])
    @ring.destroy
    respond_to do |format|

      format.html
      format.js

    end
    #redirect_to user_index_path
  end



  private

  def top_params
    params.require(:topology).permit(:ip, :port25, :port26, :port27, :port28, :max_value)
  end


  def ring_params
    params.require(:ring).permit(:pool, :vlan, :aggraddress, :build)
  end

end

app/helpers/topology_helper.rb
module TopologyHelper
end

app/views/topology/_gg.html.erb
<%=  @gontop[:ring] %>

app/views/topology/_modal.html.erb
<!-- Modal - update posts -->
<%= form_for(@ring, :url => ring_upd_path(id: @ring.id), :method => :patch, remote: true) do |f| %>
    <div class="modal fade" id="myupdatepost_<%= @ring.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">

        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Edits</h4>
          </div>
          <div class="modal-body">

            <div class="field">
              <%= f.label :pool %><br>
              <%= f.text_field :pool, class: "form-control" %>
            </div>
            <div class="field">
              <%= f.label :vlan %><br>
              <%= f.text_field :vlan, class: "form-control" %>
            </div>

            <div class="field">
              <%= f.label :aggraddress %><br>
              <%= f.text_field :aggraddress, class: "form-control" %>
            </div>

          </div>
          <div class="modal-footer">
            <button type="button" id="myupdatebutton_<%= @ring.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Update", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
<% end %>
<!-- Modal -->

app/views/topology/_newform.html.erb
<% flash.each do |key, value| %>
    <%= value %>
<% end %>
<%= form_for :ring, url: topology_index_path, remote: true do |f| %>
    <p>
      <%= f.label :pool %><br>
      <%= f.text_field :pool %>
    </p>


    <p>
      <%= f.label :vlan %><br>
      <%= f.text_field :vlan %>
    </p>
    <p>
      <%= f.label :build %><br>
      <%= f.text_field :build %>
    </p>

    <p>
      <%= f.label :aggraddress %><br>
      <%= f.text_field :aggraddress %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/topology/_result.html.erb
    <tr id="my<%= @ring.id%>">

<td>
  <%= @ring.pool %>
</td>
  <td ><%= @ring.vlan %></td>
  <td>

    <%= link_to "rebuild", rebuild_path(:pool => @ring.pool, :vlan => @ring.vlan), :class => "rebuild btn btn-info", remote: true %> |
    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatepost_<%= @ring.id %>">
      Edit
    </button> |
    <%= link_to "Удалить", topology_path(@ring.id) , method: :delete, data: { confirm: 'Вы уверены?' },:class => "btn btn-danger", remote: true %>


  </td>
  <td class="status">

    <%= image_tag('loader.gif', :size => "30x30", :class => 'loading loader')  %>
    <%= image_tag('Check.png', :size => "30x30", :class => 'loading succes') %>

  </td>
</tr>

app/views/topology/create.js.erb
$("tbody").append("<%= j render 'modal'%>");
$("tbody").append("<%= j render 'result'%>");

app/views/topology/destroy.js.erb
$("tr#my<%= @ring.id%>").fadeOut();

app/views/topology/index.html.erb
<%= javascript_include_tag "topology.js"%>
<%= stylesheet_link_tag 'topology' %>

<div class="panel-group" style="width: 90%; padding-left: 10%;">
  <div class="panel panel-primary" >
    <div class="panel-heading">
      <div id="ring_option" style="float: right;">

        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span></button>
          <ul class="dropdown-menu">
            <li><%= link_to "Меню топологии", topology_menu_path%></li>
          </ul>
        </div>
      </div>
      <div class="ring_heading" >
        <% @ring.each do |pool| %>
            <button id="<%= pool[0].gsub(".", "") %>" class="rings btn btn-default"><%= pool[0].gsub(".", "")%></button>

        <% end %>
      </div>

    </div>
    <br>
    <div class="panel-body">
      <div id='ring_list'>
        <%@ring.each do |pool|%>
            <div id="r<%= pool[0].gsub(".", "") %>"style ="display: none;" class='tr'>
              <div class="btn-group" style="float: left;">
                <% pool[1].sort_by { |a| a.split('.')[-1].to_i}.each do |ring| %>
                    <!--<button type="button" class="rings btn btn-default "><%#= link_to ring.split('.')[-1], topology_index_path(:ring => pool), remote: true%></button>-->
                    <%= button_to ring.split('.')[-1], show_topology_path(:ring => ring), :class=>"show_form rings btn btn-default", remote: true%>

                <% end %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">X</span>
    <p><div id="holder" style="height: 700px;"></div></p>
  </div>


</div>

<div class="topology_well">
  <div id="map3" style="width: 100%; height: 100%; border-color: #2E2F30; border: solid black; "></div>
</div>

<div id="map"></div>


<div id="result"></div>
<!--<script async defer-->
<!--src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAhlDgVYvkzkEd_GLNlg0BVO728ZTzgEWI">-->
<!--</script>-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAhlDgVYvkzkEd_GLNlg0BVO728ZTzgEWI" type="text/javascript"></script>
<script src="https://cdn.sobekrepository.org/includes/gmaps-markerwithlabel/1.9.1/gmaps-markerwithlabel-1.9.1.min.js"></script>

app/views/topology/menu.html.erb
<%= javascript_include_tag "topology.js" %>


<div class="container">

  <div class="row">
    <div class="text-center">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#mynewring">
        Новое кольцо
      </button>

      <div class="modal fade" id="mynewring" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Новое Кольцо</h4>
            </div>
            <div class="modal-body">
              <%= render 'newform'%>


            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>
      <!-- end modal-->




    </div>
  </div>

  <br>
  <table class="table user-list">
    <thead>
    <tr>
      <th style="width: 5%;"><span>Кольцо</span></th>
      <th style="width: 5%;"><span>Vlan</span></th>
      <th style="width: 10%;" ><span>Действие</span></th>
      <th style="width: 15%;"><span>Статус</span></th>

    </tr>
    </thead>
    <tbody>

    <% @ring_list.each do |pool| %>


        <!-- Modal - update posts -->
        <%= form_for pool, :url => ring_upd_path(id: pool.id), :method => :patch, remote: true do |f| %>
            <div class="modal fade" id="myupdatepost_<%= pool.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Edit</h4>
                  </div>
                  <div class="modal-body">

                    <div class="field">
                      <%= f.label :pool %><br>
                      <%= f.text_field :pool, class: "form-control" %>
                    </div>
                    <div class="field">
                      <%= f.label :vlan %><br>
                      <%= f.text_field :vlan, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= f.label :aggraddress %><br>
                      <%= f.text_field :aggraddress, class: "form-control" %>
                    </div>

                  </div>
                  <div class="modal-footer">
                    <button type="button" id="myupdatebutton_<%= pool.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= submit_tag "Update", class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
        <!-- Modal -->

        <% if pool.aggraddress.nil? %>

            <tr id='my<%= pool.id %>' style='background-color: red'>
        <% else %>
            <tr id="my<%= pool.id%>">
        <% end %>
        <td >

          <%= link_to pool.pool, topology_path(pool.id) %>

        </td>

        <td ><%= pool.vlan%></td>
        <td><%= link_to "rebuild", rebuild_path(:pool => pool.pool, :vlan => pool.vlan), :class => "rebuild btn btn-info", remote: true %> |
          <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatepost_<%= pool.id %>">
            Edit
          </button> |
          <%= link_to "Удалить", topology_path(pool.id) , method: :delete, data: { confirm: 'Вы уверены?' },:class => "btn btn-danger", remote: true %>


        </td>
        <td class="status">
          <%= image_tag('loader.gif', :size => "30x30", :class => 'loading loader')  %>
          <%= image_tag('Check.png', :size => "30x30", :class => 'loading succes') %> |
          last log: <%= pool.topology_info.notification unless pool.topology_info.nil?%> |  last update: <%= pool.topology_info.updated_at.strftime("%Y-%m-%d %H:%M") unless pool.topology_info.nil?%>

        </td>
        </tr>
    <% end %>

    </tbody>
  </table>
</div>

app/views/topology/show.html.erb
<div style="padding-left: 10%; padding-right: 15%; ">
<% @ring.topology.each do |switch| %>
    <div class="well well-lg">

    <%= form_for  switch, url: topology_path(id: switch.id) do |f|%>

        <%= f.text_field :ip%>

        <%= f.text_field :port25%>

        <%= f.text_field :port26%>

        <%= f.text_field :port27%>

        <%= f.text_field :port28%>

        <%= f.text_field :max_value %>


        <%= f.submit "изменить", :class => "btn btn-primary", remote: true%>
          <%= link_to "Удалить", ring_destroy_path(switch.id) , method: :delete, data: { confirm: 'Вы уверены?' },:class => "btn btn-danger", remote: true %>
    <% end %>
    </div>
<% end %>
<br>
<div class="well">
<%= form_for  :topology, url: ring_add_path(id: @ring.id) do |f|%>
    <%= f.text_field :ip %>
    <%= f.text_field :port25 %>
    <%= f.text_field :port26 %>
    <%= f.text_field :port27 %>
    <%= f.text_field :port28 %>
    <%= f.text_field :max_value %>
    <%= f.submit "Добавить", :class => "btn btn-primary", remote: true %>

<% end %>
</div>
</div>