config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root 'graphic#index'
  get 'xlss' => 'graphic#xlss'
  post 'xlss' => 'graphic#xlss'
  post 'rebuild' => 'topology#rebuild'
  get 'rebuild' => 'topology#rebuild'
  get 'check_email', to: 'user#check_email'
  get 'check_mac', to: 'switches#check_mac'
  get 'adminpanel' , to: 'adminpanel#index'
  post '/region', to: 'adminpanel#region_create', as: 'region_index'
  get '/region', to: 'adminpanel#region_create'
  post '/group', to: 'adminpanel#group_create', as: 'group_index'
  get '/group', to: 'adminpanel#group_create'
  patch '/group', to: 'adminpanel#group_update'
  post '/group_perm', to: 'adminpanel#group_perm', as: 'group_perm'
  get '/group_perm', to: 'adminpanel#group_perm'
  #get 'sessions' => 'sessions#new', as: 'sessions_new'
  get 'sessions/login' => 'sessions#login'
  post 'sessions/login' => 'sessions#login'
  get 'logout' => 'sessions#logout'
  post 'logout' => 'sessions#logout'
  get 'graphic/month' => 'graphic#month'
  post 'graphic/month' => 'graphic#month'
  get 'group_region_perm' => 'adminpanel#group_region_perm'
  post 'group_region_perm' => 'adminpanel#group_region_perm'
  get 'aggr_report' => 'switches#aggr_report'
  post 'aggr_report' => 'switches#aggr_report'
  patch 'change_password' => 'user#change_password'
  post 'forgot_password' => 'user#forgot_password'
  get 'forgot_password' => 'user#forgot_password'
  get 'reset_password' => 'user#reset_password'
  post 'reset_password' => 'user#reset_password'
  patch '/region', to: 'adminpanel#region_update'
  delete '/region/:id(.:format)', to: 'adminpanel#region_destroy', as: 'region_destroy'
  delete '/group/:id(.:format)', to: 'adminpanel#group_destroy', as: 'group_destroy'
  post 'managerings' => 'managerings#index'
  get 'managerings' => 'managerings#index'
  patch 'ring/:id(.:format)' => 'topology#ring_update', as: 'ring_upd'
  post 'ring_add' => 'topology#ring_add'
  delete '/ring/:id(.:format)', to: 'topology#ring_top_del', as: 'ring_destroy'
  #get 'ring' => 'topology#ring_update'
  post 'show_topology' => 'topology#index'
  get 'topology_menu' => 'topology#menu'
  post 'synchronize' => 'switches#synchronize'
  get 'stolen_list' => 'switches#stolen_list'
  get 'sw_loggs_event' => 'sw_loggs#event_notice'
  get 'xml_user' => 'user#xml_user'
  get 'ports_error_count' => 'port_errors#errors_count'
  get 'sw_instaled_list_path' => 'switches#inst_change_list'
post 'notify_port_error' => 'port_errors#notify'

  resources :user
  resources :switches
  resources :graphic
  resources :transport
  resources :topology
  resources :sw_loggs
  resources :sw_loggs_filter, :controller => "sw_loggs"
  resources :port_errors
#resources :sessions
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monstaff</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'bootstrap'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Monstaff</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active">
        <li><%= link_to "График", graphic_index_path  %> </li>
        <li><%= link_to "Календарь", graphic_month_path %></li>
        <li><%= link_to "Добавитьграфик", new_graphic_path  %></li>
        <li><%= link_to "Список сотрудников", user_index_path %></li>
        <li><%= link_to "Регистрация", new_user_path %></li>

        <li><%= link_to port_errors_path  do %>
            Port Error <%= content_tag :span, port_error_count, id: 'PortErrorVal', class: 'badge' %>
        <% end %>
        </li>
        <li><%= link_to "Logg", sw_loggs_path %> </li>

        <li>
          <a class=" dropdown-toggle " data-toggle="dropdown" href="#">

            <span >Мониторниг</span><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Добавить тех. работы", transport_index_path %><span class="icon-wrench"></span></li>


            <li> <%= link_to "Разделение колец", managerings_path %>
              <span class="icon-wrench"></span></li>

            <li><%= link_to "Топология(beta)", topology_index_path %><span class="icon-wrench"></span></li>
            <li><%= link_to "Отчет по коммутаторам", switches_path%><span class="icon-trash"></span> </li>
            <li><%= link_to "Отчет по агрегациям и ядрам", aggr_report_path%><span class="icon-trash"></span> </li>

          </ul>
        </li>



      </ul>
      <% if current_user %>
          <ul class="nav navbar-nav navbar-right" style="padding-right: 1%;">
            <div class="span2" style="padding-top: 3%; ">
              <div class="btn-group">
                <a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">

                  <span class="icon-cog icon-white" style="padding-right: 5%;"><%= current_user.fullname %> </span><span class="caret"></span>
                </a>
                <ul class="dropdown-menu">

                  <% if current_user.group.group_type == "admin" %>
                      <li><%= link_to "Админка", adminpanel_path %><span class="icon-wrench"></span></li>
                      <% end%>


                  <li><%= link_to "Профиль", user_path(current_user) %><span class="icon-wrench"></span></li>
                  <li> <%= %>
                    <span class="icon-wrench"></span></li>
                  <li> <%= %>
                    <span class="icon-wrench"></span></li>

                  <li><%= link_to "Выход", logout_path %><span class="icon-wrench"></span></li>
                  <li><span class="icon-trash"></span> </li>
                </ul>
              </div>
            </div>


          </ul>


      <% else %>





      <% end %>
    </div>
    </div>
  </nav>


  <!--Group permission content-->
<% if current_user.present? and  current_user.group.group_type == "admin" %>

      <div class="dropdown" style="float: right; padding-right: 20px;" >
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Доступ к странице
          <span class="caret"></span></button>
        <ul class="dropdown-menu">

          <%= form_for :group_perm, url: group_perm_path(:url_path => params[:controller].capitalize + "Controller" + params[:action]), remote: true  do |perm| %>
              <% Group.all.each do |g| %>
                  <li><%= g.name %>:

                    <%= check_box_tag 'group_ids[]', g.id, g.GroupPermission.where(url_path: params[:controller].capitalize + "Controller" + params[:action]).map(&:group_id).include?(g.id)  %></li>
              <% end %>
              <%= perm.submit "изменить", :class=>"btn btn-primary btn-xs" %>
          <% end %>
        </ul>
      </div>
  <% else %>
  <% end %>
  <!--end group perm-->
  <%= yield %>
  </body>
</html>

app/views/layouts/special_layout.html.erb
layout